version: "3.8"
services:
  postgres-remix:
    image: "postgres:15"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5434:5432"
    volumes:
      - ".pgdata/remix-app:/var/lib/postgresql/data"